/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/score': typeof ScoreRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/': typeof GoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/score': typeof ScoreRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals': typeof GoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/score': typeof ScoreRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/': typeof GoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/insights'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/score'
    | '/goals/$goalId'
    | '/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/insights'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/score'
    | '/goals/$goalId'
    | '/goals'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/insights'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/score'
    | '/goals/$goalId'
    | '/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ScoreRoute: typeof ScoreRoute
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ScoreRoute: ScoreRoute,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsIndexRoute: GoalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
